version: "2.1"

services:
  lwaftr:
    build: src/
    privileged: true
    tty: true
    stdin_open: true
    ports:
      - "22"
      - "830"
    environment:
      - LICENSE=license-eval.txt
      - IMAGE=junos-vmx-x86-64-17.3B1.1.qcow2
      - PUBLICKEY=id_rsa.pub
      - CONFIG=lwaftr.conf.txt
      - INTERFACES=03:00.0/10 04:00.0/12
    volumes:
      - $PWD:/u:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
      net-xe0:
        ipv4_address: 172.20.1.16
      net-xe1:
        ipv4_address: 172.20.2.16

  packetblaster:
    build: packetblaster/
    privileged: true
    tty: true
    stdin_open: true
    command: --b4 2001:db8::40,10.10.0.0,1024 --aftr 2001:db8:ffff::100 --count 60000 --rate 0.010 --size 128
    depends_on:
      - lwaftr
    networks:
      net-xe0:
        ipv4_address: 172.20.1.254
        ipv6_address: fd00:4601::100

  b4cpe:
    build: b4cpe/
    privileged: true
    tty: true
    stdin_open: true
    command: 193.5.1.2 1024-2047 fd00:4602::16 fd00:4602::16
    depends_on:
      - lwaftr
    networks:
      net-xe1:
        ipv6_address: fd00:4602::1001

  server:
    build: server/
    privileged: true
    tty: true
    stdin_open: true
    depends_on:
      - lwaftr
    networks:
      net-xe1:
        ipv4_address: 172.20.2.254

networks:
  default:
  net-xe0:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.20.1.0/24
        - subnet: fd00:4601::/64
  net-xe1:
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.20.2.0/24
        - subnet: fd00:4602::/64
